//15 Find the Difference
//You are given two strings s and t.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Return the letter that was added to t.
//
//
//
//Example 1:
//
//Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.
//Example 2:
//
//Input: s = "", t = "y"
//Output: "y"


import java.util.*;

public class str_15_findTheDifference {

    public static char findTheDifference(String s, String t) {
         if(t.length()>s.length()) {
             s=s+" ";
         }
         char result='r';
         char[] x=s.toCharArray();
         char[] y=t.toCharArray();
         Arrays.sort(x);
         Arrays.sort(y);
         for(int i=0;i<t.length();i++) {
             if(x[i]==y[i]) {
                 continue;
             }
             else {
                 result=y[i];
             }
         }
     return result;
     }


    public static char findTheDifferenceUsingXor(String s, String t) {
        char c = 0;
        for(char cs : s.toCharArray()) c ^= cs;
        for(char ct : t.toCharArray()) c ^= ct;
        return c;
    }
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter a string 1 : ");
        String str1 = sc.next();
        System.out.println("Enter a string 2 : ");
        String str2 = sc.next();
        System.out.println(findTheDifference(str1, str2));
        System.out.println(findTheDifferenceUsingXor(str1,str2));

    }
}
